# Importação

In [ ]:
import pandas as pd
df = pd.read_csv('bq-results-20260904-205126-1788555238314.csv')

In [44]:
pd.set_option('display.float_format', lambda x: '%.2f' % x)

# Validação

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 23439 entries, 0 to 23438
Data columns (total 30 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   report_date                  23439 non-null  datetime64[ns]
 1   campaign_key                 23439 non-null  object
 2   campaign_name                23439 non-null  object
 3   platform                     23439 non-null  object
 4   campaign_group               23439 non-null  object
 5   funnel_stage                 23439 non-null  object
 6   campaign_key_type            23439 non-null  object
 7   receita                      14134 non-null  float64
 8   orders                       14134 non-null  float64
 9   visits                       14134 non-null  float64
 10  investimento                 17290 non-null  float64
 11  impressions                  17263 non-null  float64
 12  clicks                       16929 non-null  float64
 13  roas                         7727 non-null   float64
 14  receita_safe_ad              14134 non-null  float64
 15  receita_excecao_manual       14134 non-null  float64
 16  receita_pmax_sem_anuncio     14134 non-null  float64
 17  receita_por_nome_campanha    14134 non-null  float64
 18  receita_outro                14134 non-null  float64
 19  receita_anuncio_ambiguo      14134 non-null  float64
 20  receita_nao_casado           14134 non-null  float64
 21  investimento_anuncio         17339 non-null  float64
 22  investimento_campanha        17290 non-null  float64
 23  pct_receita_assertiva        6479 non-null   float64
 24  pct_receita_anuncio_ambiguo  6479 non-null   float64
 25  pct_receita_assertiva_alta   6479 non-null   float64
 26  pct_investimento_anuncio     16069 non-null  float64
 27  motivos_receita              14134 non-null  object
 28  motivos_investimento         16069 non-null  object
 29  mes                          23439 non-null  int32
dtypes: datetime64[ns](1), float64(20), int32(1), object(8)
memory usage: 5.5+ MB

In [46]:
df.duplicated().sum()

np.int64(0)

In [47]:
(df.isnull().sum() / len(df)) * 100

report_date                    0.00
campaign_key                   0.00
campaign_name                  0.00
platform                       0.00
campaign_group                 0.00
funnel_stage                   0.00
campaign_key_type              0.00
receita                       39.70
orders                        39.70
visits                        39.70
investimento                  26.23
impressions                   26.35
clicks                        27.77
roas                          67.03
receita_safe_ad               39.70
receita_excecao_manual        39.70
receita_pmax_sem_anuncio      39.70
receita_por_nome_campanha     39.70
receita_outro                 39.70
receita_anuncio_ambiguo       39.70
receita_nao_casado            39.70
investimento_anuncio          26.03
investimento_campanha         26.23
pct_receita_assertiva         72.36
pct_receita_anuncio_ambiguo   72.36
pct_receita_assertiva_alta    72.36
pct_investimento_anuncio      31.44
motivos_receita               39.70
motivos_investimento          31.44
mes                            0.00
dtype: float64

In [48]:
df[df["receita"].isnull()].head()

,report_date,campaign_key,campaign_name,platform,campaign_group,funnel_stage,campaign_key_type,receita,orders,visits,...,receita_nao_casado,investimento_anuncio,investimento_campanha,pct_receita_assertiva,pct_receita_anuncio_ambiguo,pct_receita_assertiva_alta,pct_investimento_anuncio,motivos_receita,motivos_investimento,mes
27,2025-11-03,name|azul|bing ads|brv_va_bing_dmax_lf_aon_pass,BRV_VA_BING_DMAX_LF_AON_PASS,Bing Ads,AON,Conversão,name,NaN,NaN,NaN,...,NaN,0.00,6360.52,NaN,NaN,NaN,0.00,NaN,campanha,11
26,2025-11-03,id|azul|meta ads|120233220400040726,VML_VA_META_SOCIAL_MF_LEADS-AZUL-FRIDAY_PASS,Meta Ads,VML_VA_META_SOCIAL_MF_LEADS-AZUL-FRIDAY_PASS,Consideração,id,NaN,NaN,NaN,...,NaN,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,11
25,2025-11-03,id|azul|google ads|18185234105,BRV_VA_GOOGLE_SEARCH_LF_AON-EUA-NBRD_PASS,Google Ads,AON-EUA-NBRD,Conversão,id,NaN,NaN,NaN,...,NaN,7929.71,0.00,NaN,NaN,NaN,100.00,NaN,anuncio,11
24,2025-11-03,id|azul|meta ads|120211831577200726,VML_VA_META_SOCIAL_MF_AON_PASS,Meta Ads,VML_VA_META_SOCIAL_MF_AON_PASS,Consideração,id,NaN,NaN,NaN,...,NaN,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,11
23,2025-11-03,id|azul|google ads|22969988808,AZ_VA_GOOGLE_YOUTUBE_MF_CONGONHAS_PASS,Google Ads,AZ_VA_GOOGLE_YOUTUBE_MF_CONGONHAS_PASS,Consideração,id,NaN,NaN,NaN,...,NaN,6322.24,0.01,NaN,NaN,NaN,100.00,NaN,anuncio + campanha,11

In [63]:
total_linhas_plataforma = df.groupby('platform').size()
total_linhas_plataforma

platform
Awin           302
Bing Ads      5285
Criteo         277
DV360           50
Google Ads    8543
Kayak         3788
Meta Ads      1535
RTB            935
Skyscanner     976
Taboola        976
UOL            502
Vivo           270
dtype: int64

In [49]:
nulos_receita = df[df["receita"].isnull()]
nulos_receita.groupby("platform")["investimento"].agg(["count", "sum", "mean"])

            count        sum     mean
platform
Awin          302 3785941.75 12536.23
Bing Ads     1724 4546537.29  2637.20
Criteo         98  280077.87  2857.94
DV360          41  202743.94  4944.97
Google Ads   1216 4551984.40  3743.41
Kayak        3740 1207182.84   322.78
Meta Ads      374  732507.91  1958.58
RTB           557 1021545.12  1834.01
Skyscanner    976 1611718.01  1651.35
Taboola        12     406.43    33.87
UOL            31   13978.83   450.93
Vivo          185  229191.46  1238.87

In [65]:
total_linhas_plataforma = df.groupby('platform').size()

nulos_receita = df[df["receita"].isnull()]
nulos_por_plataforma = nulos_receita.groupby('platform').size()

pct_nulo_plataforma = nulos_por_plataforma / total_linhas_plataforma * 100
pct_nulo_plataforma.sort_values(ascending=False)

platform
Awin         100.00
Kayak        100.00
Skyscanner   100.00
DV360         82.00
Vivo          68.52
RTB           59.68
Criteo        35.38
Bing Ads      32.62
Meta Ads      24.36
Google Ads    14.23
UOL            6.18
Taboola        1.23
dtype: float64

Algumas plataformas (Awin, Kayak, Skyscanner, e em menor grau DV360, Vivo e RTB) têm taxas de
nulo muito altas (a partir de 59%, chegando a 100%). Isso não parece ser falha aleatória de coleta — é mais
provável que sejam canais onde a receita simplesmente não é atribuída diretamente na origem dos dados.

Já Google Ads, UOL, Taboola, Meta Ads, Bing Ads e Criteo têm taxas de nulo bem mais baixas (abaixo de 40%),
indicando que a atribuição de receita funciona de forma mais direta nesses canais.

In [51]:
df["campaign_key"].value_counts()

campaign_key
name|azul|bing ads|brv_va_bing_search_lf_marca_pass               302
id|azul|google ads|18482497357                                    302
id|azul|google ads|20417584768                                    302
id|azul|google ads|11382534426                                    302
name|azul|kayak|não identificado                                  302
                                                                 ...
id|azul|google ads|24184434916                                      1
name|azul|kayak|azulfdrt pt_br frontdoor flight compare to          1
name|azul|rtb|não identificado                                      1
name|azul|rtb|brv_va_rtb-house_display_lf_sazonal_pass_com-aic      1
name|azul|rtb|brv_va_rtb-house_display_lf_sazonal_pass_sem-aic      1
Name: count, Length: 278, dtype: int64

In [52]:
df["campaign_group"].value_counts()

campaign_group
NÃO IDENTIFICADO                                4376
COPA-DO-MUNDO                                    953
AON                                              862
INLINE                                           751
DATA-DUPLA                                       745
                                                ...
3.3                                                8
20OFF                                              6
VML_VA_META_SOCIAL_MF_LEADS-AZUL-FRIDAY_PASS       3
ANIVERSARIO-17-ANOS                                2
PROMOCAO-3-3                                       1
Name: count, Length: 99, dtype: int64

In [53]:
df["receita"].value_counts()

receita
0.00       7655
100.44        4
95.70         4
105.05        4
70.30         4
           ...
191.38        1
358.06        1
571.45        1
1296.70       1
5602.07       1
Name: count, Length: 6407, dtype: int64

In [54]:
df["motivos_investimento"].value_counts()

motivos_investimento
campanha              10211
anuncio                4882
anuncio + campanha      976
Name: count, dtype: int64

In [55]:

df["report_date"].value_counts()

report_date
2026-06-24    121
2026-07-15    120
2026-07-16    119
2026-07-13    119
2026-07-21    119
             ...
2025-11-08     31
2025-11-07     29
2025-11-06     28
2025-11-04     28
2025-11-03     28
Name: count, Length: 302, dtype: int64

In [56]:
df["campaign_name"].value_counts()

campaign_name
NÃO IDENTIFICADO                                      605
BRV_VA_GOOGLE_PMAX_LF_AON-MARCA_PASS                  302
BRV_VA_GOOGLE_SEARCH_LF_AON-CONCORRENTES-NBRD_PASS    302
BRV_VA_BING_SEARCH_LF_MARCA_PASS                      302
BRV_VA_GOOGLE_SEARCH_LF_AON-MARCA-BRD_PASS            302
                                                     ...
BRV_VA_RTB-HOUSE_DISPLAY_LF_SAZONAL_PASS_COM-AIC        1
BRV_VA_GOOGLE_PMAX_LF_PROMOCAO-3-3_PASS                 1
BRV_VA_RTB-HOUSE_DISPLAY_LF_SAZONAL_PASS_SEM-AIC        1
BRV_VA_BING_DMAX_LF_ANOITECEURJ_PASS                    1
AZULFDRT PT_BR FRONTDOOR FLIGHT COMPARE TO              1
Name: count, Length: 272, dtype: int64

In [57]:
df["platform"].value_counts()

platform
Google Ads    8543
Bing Ads      5285
Kayak         3788
Meta Ads      1535
Taboola        976
Skyscanner     976
RTB            935
UOL            502
Awin           302
Criteo         277
Vivo           270
DV360           50
Name: count, dtype: int64

In [58]:
df["motivos_investimento"].value_counts()

motivos_investimento
campanha              10211
anuncio                4882
anuncio + campanha      976
Name: count, dtype: int64

In [59]:
df["roas"].value_counts()

roas
0.00     3305
0.03        1
2.66        1
1.41        1
0.22        1
         ...
37.21       1
4.04        1
0.52        1
0.05        1
0.11        1
Name: count, Length: 4423, dtype: int64

In [60]:
df.head(10)

,report_date,campaign_key,campaign_name,platform,campaign_group,funnel_stage,campaign_key_type,receita,orders,visits,...,receita_nao_casado,investimento_anuncio,investimento_campanha,pct_receita_assertiva,pct_receita_anuncio_ambiguo,pct_receita_assertiva_alta,pct_investimento_anuncio,motivos_receita,motivos_investimento,mes
0,2025-11-03,id|azul|google ads|6504006924,BRV_VA_GOOGLE_SEARCH_LF_AON-MARCA-BRD_PASS,Google Ads,AON-MARCA-BRD,Conversão,id,20696.29,42.00,731.00,...,0.00,36402.57,0.00,100.00,0.00,100.00,100.00,safe_ad,anuncio,11
27,2025-11-03,name|azul|bing ads|brv_va_bing_dmax_lf_aon_pass,BRV_VA_BING_DMAX_LF_AON_PASS,Bing Ads,AON,Conversão,name,NaN,NaN,NaN,...,NaN,0.00,6360.52,NaN,NaN,NaN,0.00,NaN,campanha,11
26,2025-11-03,id|azul|meta ads|120233220400040726,VML_VA_META_SOCIAL_MF_LEADS-AZUL-FRIDAY_PASS,Meta Ads,VML_VA_META_SOCIAL_MF_LEADS-AZUL-FRIDAY_PASS,Consideração,id,NaN,NaN,NaN,...,NaN,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,11
25,2025-11-03,id|azul|google ads|18185234105,BRV_VA_GOOGLE_SEARCH_LF_AON-EUA-NBRD_PASS,Google Ads,AON-EUA-NBRD,Conversão,id,NaN,NaN,NaN,...,NaN,7929.71,0.00,NaN,NaN,NaN,100.00,NaN,anuncio,11
24,2025-11-03,id|azul|meta ads|120211831577200726,VML_VA_META_SOCIAL_MF_AON_PASS,Meta Ads,VML_VA_META_SOCIAL_MF_AON_PASS,Consideração,id,NaN,NaN,NaN,...,NaN,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,11
23,2025-11-03,id|azul|google ads|22969988808,AZ_VA_GOOGLE_YOUTUBE_MF_CONGONHAS_PASS,Google Ads,AZ_VA_GOOGLE_YOUTUBE_MF_CONGONHAS_PASS,Consideração,id,NaN,NaN,NaN,...,NaN,6322.24,0.01,NaN,NaN,NaN,100.00,NaN,anuncio + campanha,11
22,2025-11-03,id|azul|google ads|21500935126,VML_VA_GOOGLE_DISPLAY_LF_US-PASSENGER_PASS,Google Ads,VML_VA_GOOGLE_DISPLAY_LF_US-PASSENGER_PASS,Conversão,id,NaN,NaN,NaN,...,NaN,1243.87,0.00,NaN,NaN,NaN,100.00,NaN,anuncio,11
21,2025-11-03,name|azul|bing ads|brv_va_bing_search_lf_inter...,BRV_VA_BING_SEARCH_LF_INTERNACIONAL_PASS,Bing Ads,INTERNACIONAL,Conversão,name,NaN,NaN,NaN,...,NaN,0.00,6682.18,NaN,NaN,NaN,0.00,NaN,campanha,11
19,2025-11-03,id|azul|google ads|22858128667,BRV_VA_GOOGLE_SEARCH_LF_AON-CANCELAMENTO-BRD_PASS,Google Ads,AON-CANCELAMENTO-BRD,Conversão,id,NaN,NaN,NaN,...,NaN,206.59,0.00,NaN,NaN,NaN,100.00,NaN,anuncio,11
18,2025-11-03,name|azul|bing ads|brv_va_bing_search_lf_conco...,BRV_VA_BING_SEARCH_LF_CONCORRENTES_PASS,Bing Ads,CONCORRENTES,Conversão,name,NaN,NaN,NaN,...,NaN,0.00,18339.67,NaN,NaN,NaN,0.00,NaN,campanha,11

# Tratamento

In [61]:
df['report_date'] = df['report_date'].str.strip()

AttributeError: Can only use .str accessor with string values!

In [ ]:
df["report_date"] = pd.to_datetime(
    df["report_date"],
    format="%Y-%m-%d"
)

## Análise

In [ ]:
df = df.sort_values(by="report_date")
df

,report_date,campaign_key,campaign_name,platform,campaign_group,funnel_stage,campaign_key_type,receita,orders,visits,...,receita_anuncio_ambiguo,receita_nao_casado,investimento_anuncio,investimento_campanha,pct_receita_assertiva,pct_receita_anuncio_ambiguo,pct_receita_assertiva_alta,pct_investimento_anuncio,motivos_receita,motivos_investimento
0,2025-11-03,id|azul|google ads|6504006924,BRV_VA_GOOGLE_SEARCH_LF_AON-MARCA-BRD_PASS,Google Ads,AON-MARCA-BRD,Conversão,id,20696.29,42.0,731.0,...,0.00,0.0,36402.57,0.00,100.0,0.0,100.0,100.0,safe_ad,anuncio
27,2025-11-03,name|azul|bing ads|brv_va_bing_dmax_lf_aon_pass,BRV_VA_BING_DMAX_LF_AON_PASS,Bing Ads,AON,Conversão,name,NaN,NaN,NaN,...,NaN,NaN,0.00,6360.52,NaN,NaN,NaN,0.0,NaN,campanha
26,2025-11-03,id|azul|meta ads|120233220400040726,VML_VA_META_SOCIAL_MF_LEADS-AZUL-FRIDAY_PASS,Meta Ads,VML_VA_META_SOCIAL_MF_LEADS-AZUL-FRIDAY_PASS,Consideração,id,NaN,NaN,NaN,...,NaN,NaN,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN
25,2025-11-03,id|azul|google ads|18185234105,BRV_VA_GOOGLE_SEARCH_LF_AON-EUA-NBRD_PASS,Google Ads,AON-EUA-NBRD,Conversão,id,NaN,NaN,NaN,...,NaN,NaN,7929.71,0.00,NaN,NaN,NaN,100.0,NaN,anuncio
24,2025-11-03,id|azul|meta ads|120211831577200726,VML_VA_META_SOCIAL_MF_AON_PASS,Meta Ads,VML_VA_META_SOCIAL_MF_AON_PASS,Consideração,id,NaN,NaN,NaN,...,NaN,NaN,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23355,2026-08-31,name|azul|bing ads|brv_va_bing_display_lf_ofer...,BRV_VA_BING_DISPLAY_LF_OFERTAS-AZUL_PASS,Bing Ads,OFERTAS-AZUL,Conversão,name,571.45,1.0,1.0,...,0.00,0.0,NaN,NaN,100.0,0.0,0.0,NaN,por_nome_campanha,NaN
23354,2026-08-31,id|azul|google ads|23339225668,BRV_VA_GOOGLE_PMAX_LF_OFERTAS-AZUL_PASS,Google Ads,OFERTAS-AZUL,Conversão,id,1296.70,1.0,18.0,...,0.00,0.0,NaN,NaN,100.0,0.0,0.0,NaN,pmax_sem_anuncio,NaN
23353,2026-08-31,id|azul|google ads|23477987177,BRV_VA_GOOGLE_SEARCH_LF_AON-HUBS-NBRD_PASS,Google Ads,AON-HUBS-NBRD,Conversão,id,1312.16,2.0,315.0,...,1312.16,0.0,1373.07,0.00,100.0,100.0,0.0,100.0,"anuncio_ambiguo,pmax_sem_anuncio",anuncio
23365,2026-08-31,name|azul|bing ads|brv_va_bing_search_lf_aon-u...,BRV_VA_BING_SEARCH_LF_AON-US-PASSENGER-BRD_PASS,Bing Ads,AON-US-PASSENGER-BRD,Conversão,name,0.00,0.0,43.0,...,0.00,0.0,0.00,189.33,NaN,NaN,NaN,0.0,por_nome_campanha,campanha
23438,2026-08-31,name|azul|kayak|azulhbo-mob_fhboad_pt_br pt_br...,AZULHBO-MOB_FHBOAD_PT_BR PT_BR FLIGHT HBO,Kayak,NÃO IDENTIFICADO,NÃO IDENTIFICADO,name,NaN,NaN,NaN,...,NaN,NaN,0.00,20.00,NaN,NaN,NaN,0.0,NaN,campanha

In [ ]:
df.describe()

,report_date,receita,orders,visits,investimento,impressions,clicks,roas,receita_safe_ad,receita_excecao_manual,...,receita_por_nome_campanha,receita_outro,receita_anuncio_ambiguo,receita_nao_casado,investimento_anuncio,investimento_campanha,pct_receita_assertiva,pct_receita_anuncio_ambiguo,pct_receita_assertiva_alta,pct_investimento_anuncio
count,23439,1.413400e+04,14134.000000,14134.000000,17290.000000,1.726300e+04,16929.000000,7727.000000,1.413400e+04,1.413400e+04,...,14134.000000,14134.0,1.413400e+04,14134.0,17339.000000,17290.000000,6.479000e+03,6479.000000,6479.000000,16069.000000
mean,2026-04-29 06:26:48.089082368,5.352548e+04,31.017122,754.348026,3640.888178,1.567587e+05,2363.608482,49.414463,2.275873e+03,2.777134e+04,...,8115.976278,0.0,1.028274e+04,0.0,1977.540277,1657.743535,1.000000e+02,19.619651,19.191696,36.455245
min,2025-11-03 00:00:00,0.000000e+00,0.000000,1.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000e+00,...,0.000000,0.0,0.000000e+00,0.0,0.000000,0.000000,1.000000e+02,0.000000,0.000000,0.000000
25%,2026-02-23 00:00:00,0.000000e+00,0.000000,4.000000,147.885000,1.798500e+03,49.000000,0.000000,0.000000e+00,0.000000e+00,...,0.000000,0.0,0.000000e+00,0.0,0.000000,0.000000,1.000000e+02,0.000000,0.000000,0.000000
50%,2026-05-14 00:00:00,0.000000e+00,0.000000,28.000000,676.500000,1.455200e+04,279.000000,0.549523,0.000000e+00,0.000000e+00,...,0.000000,0.0,0.000000e+00,0.0,0.000000,76.680000,1.000000e+02,0.000000,0.000000,0.000000
75%,2026-07-10 00:00:00,5.867177e+03,3.000000,171.000000,2321.560000,9.313450e+04,1036.000000,6.816729,0.000000e+00,0.000000e+00,...,0.000000,0.0,0.000000e+00,0.0,417.115000,797.897500,1.000000e+02,0.000000,0.161329,100.000000
max,2026-08-31 00:00:00,4.265516e+06,2412.000000,42968.000000,476439.130000,3.610180e+07,647101.000000,274644.000000,2.097200e+06,4.022990e+06,...,615349.350000,0.0,4.112059e+06,0.0,476439.130000,136447.997444,1.000000e+02,100.000000,100.000000,100.000000
std,NaN,3.151739e+05,183.372193,3981.593194,12179.982510,6.736018e+05,9548.336052,3126.440682,2.529511e+04,2.596925e+05,...,44416.104402,0.0,1.508722e+05,0.0,11068.568283,5663.755837,1.817827e-15,38.853440,38.467838,48.131899

receita_outro
receita_nao_casado
são apenas 0

In [ ]:
teste = df.groupby(['platform'])[['receita', 'investimento','orders', 'visits', 'impressions', 'clicks', 'roas']].sum()
teste.sort_values(by='investimento')

,receita,investimento,orders,visits,impressions,clicks,roas
platform,,,,,,,
DV360,0.00,229459.25,0.00,29.00,53875414.00,1032344.00,0.00
Taboola,268102.94,247168.79,204.00,39991.00,427866203.00,837173.00,1578.56
Vivo,1314.42,280139.50,2.00,408.00,24525045.00,622290.00,0.00
Criteo,2175400.91,431211.19,1389.00,42321.00,44455075.00,136512.00,1038.64
UOL,247796.16,588621.77,86.00,4905.00,162028862.00,174106.00,0.39
RTB,469783.47,1087610.89,268.00,13610.00,184990290.00,1670270.00,1867.24
Kayak,0.00,1207182.84,0.00,0.00,147888504.00,468772.00,0.00
Meta Ads,141304.19,1329628.09,93.00,62280.00,368668515.00,2811327.00,443.35
Skyscanner,0.00,1611718.01,0.00,0.00,63598666.00,201285.00,0.00
Awin,0.00,3785941.75,0.00,0.00,0.00,0.00,0.00
Bing Ads,111548810.81,9685066.56,60108.00,1061323.00,239629992.00,2971194.00,36889.29
Google Ads,641676595.57,42467207.96,376246.00,9437088.00,988598106.00,29088255.00,340008.09

In [ ]:
teste.sort_values(by='receita')

,receita,investimento,orders,visits,impressions,clicks,roas
platform,,,,,,,
Awin,0.00,3785941.75,0.00,0.00,0.00,0.00,0.00
DV360,0.00,229459.25,0.00,29.00,53875414.00,1032344.00,0.00
Kayak,0.00,1207182.84,0.00,0.00,147888504.00,468772.00,0.00
Skyscanner,0.00,1611718.01,0.00,0.00,63598666.00,201285.00,0.00
Vivo,1314.42,280139.50,2.00,408.00,24525045.00,622290.00,0.00
Meta Ads,141304.19,1329628.09,93.00,62280.00,368668515.00,2811327.00,443.35
UOL,247796.16,588621.77,86.00,4905.00,162028862.00,174106.00,0.39
Taboola,268102.94,247168.79,204.00,39991.00,427866203.00,837173.00,1578.56
RTB,469783.47,1087610.89,268.00,13610.00,184990290.00,1670270.00,1867.24
Criteo,2175400.91,431211.19,1389.00,42321.00,44455075.00,136512.00,1038.64
Bing Ads,111548810.81,9685066.56,60108.00,1061323.00,239629992.00,2971194.00,36889.29
Google Ads,641676595.57,42467207.96,376246.00,9437088.00,988598106.00,29088255.00,340008.09

Google ads = maior investimento e maior receita

Bing ads = segundo maior investimento e segundo maior receita

Awin = terceiro maior investimento porém nenhum retorno

Skyscanner = trouxe apenas impressões e cliques

Meta Ads = trouxe receita baixa se for comparar com o que foi investido em outras plataformas que geraram mais receita

Kayak = Trouxe apenas impressões e cliques

RTB = sétimo com maior investimento porém em quarto que gerou receita

UOL

In [ ]:
filtro_awin = df[df['platform'] == 'Awin']
filtro_awin.head(10)

,report_date,campaign_key,campaign_name,platform,campaign_group,funnel_stage,campaign_key_type,receita,orders,visits,investimento,impressions,clicks,roas,receita_safe_ad,receita_excecao_manual,receita_pmax_sem_anuncio,receita_por_nome_campanha,receita_outro,receita_anuncio_ambiguo,receita_nao_casado,investimento_anuncio,investimento_campanha,pct_receita_assertiva,pct_receita_anuncio_ambiguo,pct_receita_assertiva_alta,pct_investimento_anuncio,motivos_receita,motivos_investimento
0,2025-11-03,id|azul|google ads|6504006924,BRV_VA_GOOGLE_SEARCH_LF_AON-MARCA-BRD_PASS,Awin,AON-MARCA-BRD,Conversão,id,20696.29,42.00,731.00,36402.57,86541.00,60650.00,0.57,20696.29,0.00,0.00,0.00,0.00,0.00,0.00,36402.57,0.00,100.00,0.00,100.00,100.00,safe_ad,anuncio
1,2025-11-03,id|azul|google ads|18482497357,BRV_VA_GOOGLE_SEARCH_LF_AON-CONCORRENTES-NBRD_...,Awin,AON-CONCORRENTES-NBRD,Conversão,id,5602.07,4.00,344.00,51233.72,348227.00,13341.00,0.11,0.00,0.00,5602.07,0.00,0.00,0.00,0.00,51233.72,0.00,100.00,0.00,0.00,100.00,"pmax_sem_anuncio,safe_ad",anuncio
2,2025-11-03,id|azul|google ads|20508311506,BRV_VA_GOOGLE_SEARCH_LF_AON-US-PASSENGER-BRD_PASS,Awin,AON-US-PASSENGER-BRD,Conversão,id,4802.02,2.00,51.00,3960.58,2868.00,451.00,1.21,4802.02,0.00,0.00,0.00,0.00,0.00,0.00,3960.58,0.00,100.00,0.00,100.00,100.00,"pmax_sem_anuncio,safe_ad",anuncio
3,2025-11-03,id|azul|google ads|20417584768,BRV_VA_GOOGLE_PMAX_LF_AON-MARCA_PASS,Awin,AON-MARCA,Conversão,id,3594.36,6.00,194.00,125452.90,2916938.00,67552.00,0.03,0.00,0.00,3594.36,0.00,0.00,0.00,0.00,0.00,125452.90,100.00,0.00,0.00,0.00,pmax_sem_anuncio,campanha
4,2025-11-03,id|azul|google ads|11382534426,BRV_VA_GOOGLE_SEARCH_LF_AON-GENERICA-NBRD_PASS,Awin,AON-GENERICA-NBRD,Conversão,id,3082.61,3.00,479.00,13720.68,68941.00,5224.00,0.22,2855.08,0.00,227.53,0.00,0.00,0.00,0.00,13720.68,0.00,100.00,0.00,92.62,100.00,"pmax_sem_anuncio,safe_ad",anuncio
5,2025-11-03,id|azul|google ads|21502808087,VML_VA_GOOGLE_DEMAND-GEN_LF_VANTAGEM-OTA_HOTEL,Awin,VML_VA_GOOGLE_DEMAND-GEN_LF_VANTAGEM-OTA_HOTEL,Conversão,id,1265.46,1.00,11.00,476.46,22903.00,430.00,2.66,1265.46,0.00,0.00,0.00,0.00,0.00,0.00,476.46,0.00,100.00,0.00,100.00,100.00,safe_ad,anuncio
6,2025-11-03,id|azul|google ads|22501211479,VML_VA_GOOGLE_DISPLAY_MF_OFERTAS-AON_PASS,Awin,VML_VA_GOOGLE_DISPLAY_MF_OFERTAS-AON_PASS,Consideração,id,451.40,1.00,40.00,320.46,13885.00,1513.00,1.41,451.40,0.00,0.00,0.00,0.00,0.00,0.00,320.46,0.00,100.00,0.00,100.00,100.00,safe_ad,anuncio
7,2025-11-03,id|azul|google ads|18742168531,VML_VA_GOOGLE_DEMAND-GEN_LF_AON_PASS,Awin,VML_VA_GOOGLE_DEMAND-GEN_LF_AON_PASS,Conversão,id,0.00,0.00,10.00,3109.37,85713.00,234.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,3109.37,0.00,NaN,NaN,NaN,100.00,safe_ad,anuncio
8,2025-11-03,id|azul|google ads|21780104044,VML_VA_GOOGLE_DISPLAY_MF_AON_PASS,Awin,VML_VA_GOOGLE_DISPLAY_MF_AON_PASS,Consideração,id,0.00,0.00,25.00,1489.18,70714.00,8657.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,1489.18,0.00,NaN,NaN,NaN,100.00,"anuncio_ambiguo,safe_ad",anuncio
9,2025-11-03,id|azul|google ads|21501016741,VML_VA_GOOGLE_DISPLAY_LF_VANTAGEM-OTA_HOTEL,Awin,VML_VA_GOOGLE_DISPLAY_LF_VANTAGEM-OTA_HOTEL,Conversão,id,0.00,0.00,2.00,428.64,172645.00,6157.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,428.64,0.00,NaN,NaN,NaN,100.00,safe_ad,anuncio

In [ ]:
df["mes"] = df["report_date"].dt.month

In [ ]:
testemes = df.groupby(['mes'])[['receita', 'investimento']].sum()
testemes

          receita  investimento
mes
1    5.253334e+07  4.846083e+06
2    8.717681e+07  4.995530e+06
3    1.091946e+08  8.892272e+06
4    1.038159e+08  6.273463e+06
5    9.978586e+07  5.537374e+06
6    8.057303e+07  6.407135e+06
7    6.973996e+07  5.020760e+06
8    1.186146e+08  5.173953e+06
11   1.520553e+07  9.569982e+06
12   1.988952e+07  6.234406e+06